export const appUserData = [
    {
        id: 1,
        date : '2024-12-16',
        name: 'John Doe',
        company: 'kapcon',
        mobileNo: '+1234567890',
        verification: 'Completed',
        email: 'john.doe@example.com',
    },
    {
        id: 2,
        date : '2024-12-16',
        name: 'John Doe',
        company: 'kapcon',
        mobileNo: '+1234567890',
        verification: 'Not completed',
        email: 'john.doe@example.com',
    },
    {
        id: 3,
        date : '2024-12-16',
        name: 'John Doe',
        company: 'kapcon',
        mobileNo: '+1234567890',
        verification: 'Completed',
        email: 'john.doe@example.com',
    },
    {
        id: 4,
        date : '2024-12-16',
        name: 'John Doe',
        company: 'kapcon',
        mobileNo: '+1234567890',
        verification: 'Not completed',
        email: 'john.doe@example.com',
    },
    {
        id: 5,
        date : '2024-12-16',
        name: 'John Doe',
        company: 'kapcon',
        mobileNo: '+1234567890',
        verification: 'Not completed',
        email: 'john.doe@example.com',
    },
    {
        id: 6,
        date : '2024-12-16',
        name: 'John Doe',
        company: 'kapcon',
        mobileNo: '+1234567890',
        verification: 'Not completed',
        email: 'john.doe@example.com',
    },
    {
        id: 7,
        date : '2024-12-16',
        name: 'John Doe',
        company: 'kapcon',
        mobileNo: '+1234567890',
        verification: 'Not completed',
        email: 'john.doe@example.com',
    },
    {
        id: 8,
        date : '2024-12-16',
        name: 'John Doe',
        company: 'kapcon',
        mobileNo: '+1234567890',
        verification: 'Completed',
        email: 'john.doe@example.com',
    },
    {
        id: 9,
        date : '2024-12-16',
        name: 'John Doe',
        company: 'kapcon',
        mobileNo: '+1234567890',
        verification: 'Completed',
        email: 'john.doe@example.com',
    },
]